#ifndef TEST_APP_CONFIG_H
#define TEST_APP_CONFIG_H

#define CFG_TARGET_PLATFORM_STM32_HAL 1

#define CFG_FEAT_LOG_SYSTEM 0
#define CFG_FEAT_HAL_PWR 1
#define CFG_FEAT_HAL_RTC 1
#define CFG_FEAT_HAL_ADC 1
#define CFG_FEAT_HAL_I2C 1
#define CFG_FEAT_HAL_SPI 1
#define CFG_FEAT_HAL_UART 1
#define CFG_FEAT_HAL_GPIO 1
#define CFG_FEAT_HAL_WDG 1
#define CFG_FEAT_HAL_FLASH 1
#define CFG_FEAT_RINGBUFFER_SYSTEM 1

#endif /* TEST_APP_CONFIG_H */
